<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\demo_form\Plugin\Validation\Constraint;
use Drupal\node\Entity\Node;

//Adds validation to the telephone number field
function demo_form_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if(isset($fields['field_requester_phone_number'])) {
    $fields['field_requester_phone_number']->addConstraint('TelephoneNumber',[]);
  }
}
