commerce_payment.commerce_payment_gateway.plugin.moneris_onsite:
  type: commerce_payment_gateway_configuration
  mapping:
    store_id:
      type: string
      label: 'Store ID'
    api_token:
      type: string
      label: 'API token'
    country_code:
      type: string
      label: 'Country code'
    should_pass_avs_info:
      type: boolean
      label: 'Should pass avs info'