<?php

use Drupal\Core\Entity\EntityInterface;
/**
 * Implements hook_entity_view_mode_alter().
 */
function apm_application_entity_view_mode_alter(&$view_mode, EntityInterface $entity, $context) {
  // kint($entity);
  $nodeType = null;
  if($entity->getEntityTypeId() == 'node') {
      $nodeType = $entity->getType();
  }

  // Change the view mode for application nodes
  // if ($nodeType == 'application') {
  //   $view_mode = 'application_view';
  // }

  if ($nodeType == 'application') {
    $view_mode = 'layout_test';
  }
}
